#!/bin/bash

function discover_depends {
    file=$1
    includes=$(cat $file | perl -ne '/#include\s*<(.*)>/ && print "$1\n"')
    
    for i in $includes ; do
        if [[ -f include/$i ]] ; then
            echo -n "include/$i "
        fi
    done
}

source_files=$(find * -name '*cpp' -and -not -name 'main.cpp' -and -not -name 'test_*')
mains=$(find * -name 'main_*.cpp')

cat <<- EOF
# This file was autogenerated using ./genmake.sh
# You should not have to edit this file by hand!
# If you do have to edit this file by hand please
# contact the sourceror
#
# To modify the different attributes of everything,
# check out the targets directory as it contains all
# the configuration for compilation.

TGT?=x86
MODE?=devel

.INCLUDE_DIRS += targets/\$(TGT)/
include targets/\$(TGT)/\$(MODE).mk 

default:
EOF
echo '	mkdir -p _\$(TGT)_obs/ && make all'
echo ''

objects=""

for file in $source_files ; do
    obj_file=${file/cpp/o}
    obj_file=_'$(TGT)'_obs/${obj_file//\//_}

    echo "$obj_file: $file $(discover_depends $file)"
    echo '	$(CXX) -o '$obj_file' $(CXXFLAGS) -c '$file
    echo ''

    objects=$objects' '$obj_file
done

echo 'clean:'
echo '	rm -rf _$(TGT)_obs/'
echo '	rm mercury'
echo ''
echo '_$(TGT)_obs/libmerc.a: '$objects
echo '	ar -r $@ $^'
echo ''
echo 'all: _$(TGT)_obs/libmerc.a'
echo '	$(CXX) -o _$(TGT)_obs/mercury main.cpp $(CXXFLAGS) -L _$(TGT)_obs/ -lmerc'
echo '	ln -sf _$(TGT)_obs/mercury .'
echo ''
echo 'genmake: genmake.sh'
echo '	./genmake.sh > Makefile'
echo ''
echo 'cleanall:'
echo '	rm -rf _*_obs'
echo '	rm mercury'

